name: 'chatgpt-action'
description: 'A collection of ChatGPT assistants, e.g., code viewer, labeler, assigner, etc.'
author: 'Tao He'
inputs:
  action:
    required: false
    description: 'The action to run, currently can be "review", "score"'
    default: 'code-review'
  review_beginning:
    required: false
    description: "The beginning prompt of a code review dialog"
    default: |
      Hi chatgpt, I have a pull request with title "$title" and the description is as follows,

      > $description.

      I would given you a series of patches, each of them consists of a filename and a diff snippet,
      and you need to do a brief code review, tell me any bug risk and improvement suggestion.
      You answer should be concise and in markdown format. If the patch is looks good and acceptable,
      please reply "LGTM!".
  review_patch:
    required: false
    description: 'The prompt for each chunks/patches'
    default: |
      $filename

      ```diff
      $patch
      ```
  scoring:
    required: false
    description: 'The prompt for the whole pull request'
    default: |
      Hi chatgpt, I have a pull request with title "$title" and the description is as follows,

      > $description

      I would like to give you the whole diff of the pull request and you need to given a score after
      reviewing the pull request. The score should be a number between 0 and 100 and 85 means the
      the pull request is basically acceptable. You just need to reply a number between 0 and 100,
      e.g., "85", and a comment within 30 words.

      The diff is as follows:

      ```diff
      $diff
      ```
runs:
  using: 'node16'
  main: 'dist/index.js'
